In [30]:
import numpy as np
from numpy.linalg import svd

np.random.seed(121)
a = np.random.randn(4,4)
print(np.round(a,3))

[[-0.212 -0.285 -0.574 -0.44 ]
 [-0.33   1.184  1.615  0.367]
 [-0.014  0.63   1.71  -1.327]
 [ 0.402 -0.191  1.404 -1.969]]


In [31]:
U , Sigma , Vt = svd(a)
print(U.shape , Sigma.shape , Vt.shape)
print('U matrix : `n', np.round(U, 3))
print('Sigma value : `n', np.round(Sigma, 3))
print('V transpose matrix : `n', np.round(Vt, 3))

(4, 4) (4,) (4, 4)
U matrix : `n [[-0.079 -0.318  0.867  0.376]
 [ 0.383  0.787  0.12   0.469]
 [ 0.656  0.022  0.357 -0.664]
 [ 0.645 -0.529 -0.328  0.444]]
Sigma value : `n [3.423 2.023 0.463 0.079]
V transpose matrix : `n [[ 0.041  0.224  0.786 -0.574]
 [-0.2    0.562  0.37   0.712]
 [-0.778  0.395 -0.333 -0.357]
 [-0.593 -0.692  0.366  0.189]]


In [32]:
Sigma_mat = np.diag(Sigma)

In [33]:
Sigma_mat

array([[3.4229581 , 0.        , 0.        , 0.        ],
       [0.        , 2.02287339, 0.        , 0.        ],
       [0.        , 0.        , 0.46263157, 0.        ],
       [0.        , 0.        , 0.        , 0.07935069]])

In [36]:
np.round(np.dot(np.dot(U , Sigma_mat) ,Vt) ,3 )

array([[-0.212, -0.285, -0.574, -0.44 ],
       [-0.33 ,  1.184,  1.615,  0.367],
       [-0.014,  0.63 ,  1.71 , -1.327],
       [ 0.402, -0.191,  1.404, -1.969]])

In [46]:
U_2dim , Vt_2dim ,  Sigma_mat_2dim = U[: ,:2] , Vt[:2, :] , Sigma_mat[:2 ,:2]

In [44]:
Vt_2dim

array([[ 0.04100747,  0.22367823,  0.78643002, -0.57429458],
       [-0.20019867,  0.56209596,  0.37041464,  0.71187191]])

In [47]:
Sigma_mat_2dim

array([[3.4229581 , 0.        ],
       [0.        , 2.02287339]])

In [48]:
np.round(np.dot(np.dot(U_2dim , Sigma_mat_2dim) ,Vt_2dim) ,3 )

array([[ 0.118, -0.422, -0.451, -0.303],
       [-0.265,  1.188,  1.62 ,  0.38 ],
       [ 0.083,  0.528,  1.784, -1.258],
       [ 0.305, -0.107,  1.341, -2.03 ]])

#### sklearn.decomposition.TruncatedSVD
* class sklearn.decomposition.TruncatedSVD(n_components=2, *, algorithm='randomized', n_iter=5, n_oversamples=10, power_iteration_normalizer='auto', random_state=None, tol=0.0)